name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for creating an issue in this repo. I hope you have followed Code the Conduct while making this issue'
        pr-message: 'Thank you for creating an PR in this repo. I hope you have followed Code the Conduct while making this issue'
